# Generated by Django 5.1.7 on 2025-04-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_restaurant_cuisine_restaurant_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
    ]
