# Generated by Django 5.1.7 on 2025-04-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_restaurant_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL логотипа/аватара'),
        ),
    ]
